config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yfcases do
	resources :subsigntrueas, :controller => "yfcase_subsigntruea"
	resources :subsigntruebs, :controller => "yfcase_subsigntrueb"
	resources :subsigntruecs, :controller => "yfcase_subsigntruec"
  	resources :objectbuilds do 
		resources :plusrateas, :controller => "objectbuild_plusrateas"
		resources :plusratebs, :controller => "objectbuild_plusratebs"
		member do
			get :editplusratea, :controller => "yfcase_objectbuilds"
			get :editplusrateb, :controller => "yfcase_objectbuilds"
			patch :updateplusratea , :controller => "yfcase_objectbuilds"
			patch :updateplusrateb , :controller => "yfcase_objectbuilds"
			delete :deleteplusratea , :controller => "yfcase_objectbuilds" #刪除加成人員A及加成A
			delete :deleteplusrateb , :controller => "yfcase_objectbuilds" #刪除加成人員B及加成B
			delete :deleteplusrateall , :controller => "yfcase_objectbuilds" #刪除所有加成人員及加成
		end
	end
	member do
		get :yfratingscale #YF評量表
		get :deedtax #契稅申請書
		get :realestateregistration #不動產登記
		get :complaint #訴訟狀
		get :letter #存証信函
		get :commonpropertydivision #共有物分割
		# get :sendmail #寄發信件給會計
		delete :delete_subsigntruea #刪除副署人員1
		delete :delete_subsigntrueb #刪除副署人員2
		delete :delete_subsigntruec #刪除副署人員3
		
	end
  end
  root to: "yfcases#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Yangfurails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    
    <%= wicked_pdf_stylesheet_link_tag 'pdf' -%>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@500&family=Roboto:wght@500&display=swap" rel="stylesheet">
    <!-- 下列三行要在後面才執行，不然地址無法連動 -->
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <!--<script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>-->

    <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <%= link_to 'YangFu', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <% if user_signed_in? %>
          <a class="p-2 text-white">
            (<%= current_user.first_name %><%= current_user.last_name %>)
          </a>
          <%= link_to "建立YF評量表", new_yfcase_path, class: "btn btn-info p-2" %>
          <%= link_to "登出", destroy_user_session_path, method: :delete, class: "btn btn-danger p-2" %>
        <% else %>
          <%= link_to "登入", new_user_session_path, class: "btn btn-primary p-2" %>
          <%= link_to "註冊", new_user_registration_path, class: "btn btn-success p-2" %>
        <% end %>

      </form>
    </div>
  </nav>

  <div class="container-fluid" style="padding:20px;">
    <%= yield %>
  </div>
    
</body>

</html>